name = "salix"
license = "MIT"
licenselink = "https://github.com/bouni/salix/blob/master/LICENSE.md"
description = "A fast, minimalist and responsive hugo theme for bloggers."
homepage = "https://github.com/bouni/salix"
tags = ["blog", "fast", "minimalist", "responsive", "simple", "beautiful", "tags", "pages"]
features = ["fast", "minimalist", "archive", "tags"]
min_version = "0.80.0"

[author]
    name = "bouni"
    homepage = "https://github.com/bouni"
